# Generated by Django 3.2.23 on 2023-12-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0085_auto_20231228_2351'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='unique_lft_tree',
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='unique_rgt_tree',
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('tree_id', 'lft'), name='unique_lft_tree'),
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('tree_id', 'rgt'), name='unique_rgt_tree'),
        ),
    ]
