# Generated by Django 3.2.22 on 2024-01-19 20:23

import django.db.models.constraints
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0086_auto_20231228_2354"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_lft_tree",
        ),
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_rgt_tree",
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "lft"),
                name="unique_lft_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("tree_id", "rgt"),
                name="unique_rgt_tree",
            ),
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.CheckConstraint(
                check=models.Q(("lft__lt", django.db.models.expressions.F("rgt"))),
                name="blub",
            ),
        ),
    ]
